# Generated by Django 3.1.2 on 2020-11-07 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobsForALL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Not Set Yet', max_length=25)),
                ('location', models.CharField(blank=True, default='Not Set Yet', max_length=30)),
                ('usertype', models.CharField(choices=[('employer', 'employer'), ('employee', 'employee')], default='employer', max_length=35)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='employer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
