# Generated by Django 3.1.2 on 2020-11-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsForALL', '0002_auto_20201107_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='service_type',
            field=models.CharField(choices=[(None, None), ('woodworker', 'woodworker'), ('plumber', 'plumber'), ('electricion', 'electricion')], default=None, max_length=40),
        ),
    ]
