# Generated by Django 3.1.2 on 2020-11-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsForALL', '0003_userprofile_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='service_type',
            field=models.CharField(blank=True, choices=[(None, None), ('woodworker', 'woodworker'), ('plumber', 'plumber'), ('electricion', 'electricion')], max_length=40, null=True),
        ),
    ]
