# Generated by Django 3.1.2 on 2020-11-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsForALL', '0004_auto_20201107_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='service_type',
            field=models.CharField(choices=[('NULL', 'NULL'), ('woodworker', 'woodworker'), ('plumber', 'plumber'), ('electricion', 'electricion')], default='NULL', max_length=40),
        ),
    ]
