# Generated by Django 3.1.2 on 2020-11-07 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobsForALL', '0005_auto_20201107_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('gig_type', models.CharField(choices=[('NULL', 'NULL'), ('woodworker', 'woodworker'), ('plumber', 'plumber'), ('electricion', 'electricion')], default='NULL', max_length=40)),
                ('location', models.CharField(blank=True, default='Not Set Yet', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('Poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs', to=settings.AUTH_USER_MODEL)),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs_asigned', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
