# Generated by Django 3.1.2 on 2020-11-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsForALL', '0006_gig'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='title',
            field=models.CharField(default='Untitled', max_length=40),
        ),
    ]
