# Generated by Django 3.1.2 on 2020-11-07 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JobsForALL', '0007_gig_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='Poster',
            new_name='poster',
        ),
        migrations.AlterField(
            model_name='gig',
            name='assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gigs_asigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
