# Generated by Django 3.1.2 on 2020-11-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsForALL', '0008_auto_20201107_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
