# Generated by Django 3.1.2 on 2020-11-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsForALL', '0009_gig_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
