# Generated by Django 3.1.2 on 2020-11-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobsForALL', '0010_auto_20201107_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
